title = "Custom gitleaks config"

[extend]
useDefault = true  # This keeps default rules

# Global allowlist to exclude test files from all password detection
[allowlist]
paths = [
  '''tests/.*\.test\.ts$''',
  '''tests/.*\.spec\.ts$''',
  '''__tests__/.*'''
]

[[rules]]
id = "api-key-pattern"
description = "Generic API key"
regex = '''(?i)(api[_-]?key|apikey)\s*[=:]\s*["\']?[a-zA-Z0-9]{16,}["\']?'''
tags = ["api-key"]
